@startuml
class LogComplexNumberCalculator {
- ComplexNumberCalculable calculator
- Loggable logger
+ ComplexNumberCalculator addition(ComplexNumber)
+ ComplexNumberCalculator multiplication(ComplexNumber)
+ ComplexNumber getResult()
}
class LogCalculatorFactory {
- CalculatorFactorable firstFactory
- Loggable logger
+ ComplexNumberCalculable create(ComplexNumber)
}
class Main {
+ {static} void main(String[])
}
interface Loggable {
~ void log(String)
}
interface CalculatorFactorable {
~ ComplexNumberCalculable create(ComplexNumber)
}
interface ComplexNumberCalculable {
~ ComplexNumberCalculator addition(ComplexNumber)
~ ComplexNumberCalculator multiplication(ComplexNumber)
~ ComplexNumber getResult()
}
class CalculatorFactory {
+ ComplexNumberCalculable create(ComplexNumber)
}
class ComplexNumberCalculator {
- ComplexNumber resultNumber
+ ComplexNumberCalculator addition(ComplexNumber)
+ ComplexNumberCalculator multiplication(ComplexNumber)
+ ComplexNumber getResult()
}
class ComplexNumber {
- double real
- double imaginary
+ double getReal()
+ double getImaginary()
+ String toString()
}
class Console {
- CalculatorFactorable calculatorFactory
+ void run()
- String input(String)
- ComplexNumber inputComplex(String)
}
class Logger {
+ void log(String)
}


ComplexNumberCalculable <|.. LogComplexNumberCalculator
CalculatorFactorable <|.. LogCalculatorFactory
CalculatorFactorable <|.. CalculatorFactory
ComplexNumberCalculable <|.. ComplexNumberCalculator
'Ассоциация: Класс Console содержит ссылку на объект CalculatorFactory'
Console --> CalcucatorFactory : Association
CalculatorFactory ..> Logger : uses
CalculatorFactory "1" *.. "1" ComplexNumberCalculator : creates
'Ассоциация: Класс LogCalcFactory содержит ссылку на объект CalcFactorable'
LogCalculatorFactory -- CalculatorFactorable : Association
'Зависимость: Класс Main использует класса LogCalculatorFactory для создания объектов, то есть зависит от него.'
Main --> LogCalculatorFactory : Dependency
'Реализация: Класс Logger реализует интерфейс Loggable. Logger реализует метод log(String) из интерфейса.'
Logger --|> Loggable : Implements
'Реализация: Класс CalculatorFactory реализует интерфейс CalculatorFactorable.'
CalculatorFactory --|> CalculatorFactorable : Implements
'Композиция: Класс LogComplexNumberCalculator содержит объект Calculator '
LogComplexNumberCalculator --o Calculator : Contains
'Агрегация: Класс LogComplexNumberCalculator агрегирует (содержит) объект класса ComplexNumberCalculator,
 'представляющий вычисления комплексных чисел.'
 LogComplexNumberCalculator --o ComplexNumberCalculator : Aggregation
@enduml